# Generated by Django 3.1.5 on 2021-11-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(null=True),
        ),
    ]
