# Generated by Django 3.1.5 on 2021-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20211118_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='header',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
