# Generated by Django 3.1.5 on 2021-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20211121_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='header',
            field=models.CharField(max_length=35),
        ),
    ]
