# Generated by Django 3.1.5 on 2021-11-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
    ]
