# Generated by Django 3.1.5 on 2021-11-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='notes',
        ),
        migrations.AddField(
            model_name='collections',
            name='name',
            field=models.CharField(default='Collection', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.collections'),
        ),
    ]
