# Generated by Django 3.1.5 on 2021-11-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20211126_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
    ]
