# Generated by Django 3.1.5 on 2021-11-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20211127_1417'),
        ('notes', '0009_auto_20211126_2001'),
    ]

    operations = [
    ]
