# Generated by Django 3.1.5 on 2021-11-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20211130_0927'),
        ('notes', '0011_merge_20211127_1845'),
    ]

    operations = [
    ]
