# Generated by Django 3.1.5 on 2021-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_merge_20211130_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='header',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=170),
        ),
    ]
