# Generated by Django 3.1.5 on 2021-11-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_merge_20211130_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date', 'is_important']},
        ),
    ]
