# Generated by Django 3.1.5 on 2021-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20211130_2304'),
        ('notes', '0016_auto_20211130_1707'),
    ]

    operations = [
    ]
